import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import {
  CreateRoomInputType,
  createRoomValidator,
} from "../shared/create-room-validator";
import { zodResolver } from "@hookform/resolvers/zod";
import { string } from "zod";

const Home: NextPage = () => {
  const router = useRouter();
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  // const [num, setNum] = useState(0);
  trpc.useSubscription(["randomNumber", undefined], {
    onNext(n) {
      console.log(n);
    },
  });
  // const roomId =
  const { mutate, isLoading, data } = trpc.useMutation("room.create", {
    onSuccess: data => {
      router.push(`/room/${data.id}`);
    },
  });
  const [roomId, setRoomId] = useState<string>("");
  const handleSubmit = async ({ id }: { id: string }) => {
    router.push(`/room/${id}`);
  };

  return (
    <>
      <Head>
        <title>WebRTC App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>Sub number: {num}</div> */}
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <button
          className="font-extrabold text-center text-3xl border-2 rounded p-1 m-1 opacity-70 hover:opacity-100"
          onClick={() => {
            mutate();
          }}
        >
          Create <span className="text-blue-500">Room</span>
        </button>
        <span>
          <input
            placeholder="paste room id"
            className="font-extrabold text-center text-3xl border02 rounded p-1 m-1 "
            value={roomId}
            onChange={e => setRoomId(e.target.value)}
          />
          <button
            className="font-extrabold text-center text-3xl border-2 rounded p-1 m-1 opacity-70 hover:opacity-100"
            onClick={() => {
              handleSubmit({ id: roomId });
            }}
          >
            Join <span className="text-blue-500">Room</span>
          </button>
        </span>
        <div className="py-6 text-2xl">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </div>
    </>
  );
};

export default Home;
